import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Sidebar from "@/components/Sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="h-screen">
          <div className="h-[10vh]">
            <Header />
          </div>
          <div className="grid grid-cols-12 h-[90vh]">
            <div className="col-span-1">
              <Sidebar />
            </div>
            <div className="col-span-11">{children}</div>
          </div>
        </main>
      </body>
    </html>
  );
}
